import Foundation
@testable import MomentumKit

/// docs/band-fixture.json from sector_momentum (dashboard/band_fixture.py),
/// vendored under Fixtures/. Generated by running the real Python rules, so
/// these are the reference answers. Refresh with scripts/update-fixture.sh;
/// never edit by hand.
struct BandFixture: Decodable {
    struct Band: Decodable {
        struct Rank: Decodable {
            let rank: Double
            let setup: Setup?
            let in_buy_band: Bool
        }
        let horizon: String
        let top_n: Int
        let buffer_frac: Double
        let universe_size: Int
        let exit_rank: Int
        let ranks: [Rank]
    }

    struct Series: Decodable {
        let ranks: [Double]
        let slope: Double
        let trajectory: Trajectory
    }

    struct Board: Decodable {
        struct Expected: Decodable {
            let delta_rank: String
            let trajectory: Trajectory
            let slope: Double
        }
        let name: String
        let rows: [ScoreRow]
        let expected: [String: Expected]
    }

    let fixture_version: Int
    let band: [Band]
    let series: [Series]
    let boards: [Board]

    enum LoadError: Error { case missing }

    static func load() throws -> BandFixture {
        guard let url = Bundle.module.url(forResource: "band-fixture", withExtension: "json",
                                          subdirectory: "Fixtures") else { throw LoadError.missing }
        return try JSONDecoder().decode(BandFixture.self, from: Data(contentsOf: url))
    }
}
